# -*- coding:utf-8 -*-

import django
#独立使用django的model
import sys
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "gpu_tasker.settings")
django.setup()
from gpu_info.models import GPUServer
from django.contrib.auth.models import User# pwd = os.path.dirname(os.path.realpath(__file__))
from django.contrib.auth.models import User  # os.path.dirname() 获取当前脚本所在的文件夹名称
from django.contrib.auth.models import User  # os.path.realpath(__file__) 获取当前执行脚本的绝对路径。
from django.contrib.auth.models import User  # 获取当前文件的路径
from django.contrib.auth.models import User
from task.models import GPUTask


cmds = [

    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 11314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 21314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 31314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 41314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 51314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 61314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 71314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model DiffPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-MULTI - -model MinCutPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model DiffPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset IMDB-BINARY - -model MinCutPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model DiffPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-BINARY - -model MinCutPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model DiffPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-5K - -model MinCutPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model DiffPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",
    "source /data/han/miniconda3/bin/activate;conda activate torch171_geo163;python - u gc_diff_minicut.py - -data_path / data/han/data/graph - -log_dir / home/grads/h/han/workspace/graphon/log_rebuttal / --dataset REDDIT-MULTI-12K - -model MinCutPool - -gmixup False - -seed 81314 - -log_screen False - -batch_size 128 - -lr 0.01 - -num_hidden 64 - -aug_ratio 0.2 - -aug_num 10 - -epoch 400",

 ]

for i, cmd in enumerate( cmds ):
    task_instance = GPUTask()
    task_instance.name = f"gon_diff_mincut_{i}" 
    task_instance.workspace = "/home/grads/h/han/workspace/neighbor_fairness/src"
    task_instance.memory_requirement = 4000
    task_instance.utilization_requirement = 0
    task_instance.cmd = cmd
    task_instance.user = User.objects.get(username='han')
    task_instance.status = 0
    # task_instance.assign_server = GPUServer.objects.get(hostname="datalab5.engr.tamu.edu")
    task_instance.save()
