version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: gputasker_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_DATABASE=gpu_tasker
      - MYSQL_ROOT_PASSWORD=gpu_tasker
    networks:
      - gputasker_net
    command: "--default-authentication-plugin=mysql_native_password"

  gputasker:
    image: yuhaow/gputasker:latest
    container_name: gputasker_django
    volumes:
      - ./server_log:/gpu_tasker/server_log
      - ./running_log:/gpu_tasker/running_log
      - ./private_key:/gpu_tasker/private_key
      - ./static_collected:/gpu_tasker/static_collected
      - ./uwsgi/log:/gpu_tasker/uwsgi/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - gputasker_net

  nginx:
    image: nginx:latest
    container_name: gputasker_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./static_collected:/static_collected
      - ./uwsgi/log:/gpu_tasker/uwsgi/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '8080:80'
    networks:
      - gputasker_net

networks:
  gputasker_net:
